# Generated by Django 4.1.7 on 2023-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField()),
                ('cname', models.CharField(max_length=20)),
                ('ccity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uno', models.IntegerField()),
                ('uname', models.CharField(max_length=20)),
                ('ucity', models.CharField(max_length=20)),
                ('uproject', models.CharField(max_length=20)),
                ('uassinged', models.CharField(max_length=20)),
            ],
        ),
    ]
